// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A general-purpose personal AI assistant.
 *
 * - personalAssistant - Handles conversational AI interactions.
 * - PersonalAssistantInput - The input type for the personalAssistant function.
 * - PersonalAssistantOutput - The return type for the personalAssistant function.
 */

import {ai} from '@/ai/genkit';
import {Message, Role} from 'genkit/model';
import {z} from 'genkit';
import { format } from "date-fns";
import { id as idLocale } from "date-fns/locale";

// Define the structure for a single message in the history
const MessageSchema = z.object({
  role: z.enum(['user', 'model']),
  content: z.string(),
});

const PersonalAssistantInputSchema = z.object({
  history: z.array(MessageSchema).describe('The conversation history.'),
  prompt: z.string().describe('The user\'s latest prompt.'),
});
export type PersonalAssistantInput = z.infer<typeof PersonalAssistantInputSchema>;

const PersonalAssistantOutputSchema = z.object({
  response: z.string().describe('The AI\'s response.'),
});
export type PersonalAssistantOutput = z.infer<typeof PersonalAssistantOutputSchema>;

export async function personalAssistant(input: PersonalAssistantInput): Promise<PersonalAssistantOutput> {
  return personalAssistantFlow(input);
}

const personalAssistantFlow = ai.defineFlow(
  {
    name: 'personalAssistantFlow',
    inputSchema: PersonalAssistantInputSchema,
    outputSchema: PersonalAssistantOutputSchema,
  },
  async ({history, prompt}) => {
    const formattedHistory: Message[] = history.map(msg => ({
      role: msg.role as Role,
      content: [{text: msg.content}],
    }));

    const currentDate = format(new Date(), "eeee, dd MMMM yyyy", { locale: idLocale });
    const systemPrompt = `Anda adalah asisten AI pribadi. Jawab semua pertanyaan dengan bebas dan informatif.
    Informasi penting: Tanggal hari ini adalah ${currentDate}. Gunakan informasi ini jika ada pertanyaan terkait tanggal.`;

    const response = await ai.generate({
      model: ai.model,
      system: systemPrompt,
      history: formattedHistory,
      prompt: prompt,
      config: {
        // Adjust safety settings as requested
        safetySettings: [
          {
            category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
            threshold: 'BLOCK_ONLY_HIGH',
          },
          {
            category: 'HARM_CATEGORY_HARASSMENT',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE',
          },
          {
            category: 'HARM_CATEGORY_HATE_SPEECH',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE',
          },
          {
            category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
            threshold: 'BLOCK_MEDIUM_AND_ABOVE',
          },
        ],
      },
    });

    return {response: response.text ?? ""};
  }
);
