// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow to predict egg production based on various factors.
 *
 * - predictEggProduction - Predicts egg production using AI.
 * - PredictEggProductionInput - The input type for predictEggProduction.
 * - PredictEggProductionOutput - The output type for predictEggProduction.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PredictEggProductionInputSchema = z.object({
  duckQuantity: z.number().describe('The total number of ducks.'),
  duckAgeMonths: z.number().describe('The average age of the ducks in months.'),
  duckCondition: z.string().describe('The overall health condition of the ducks (e.g., healthy, sick).'),
  feedQuality: z.string().describe('The quality of the feed being provided (e.g., high, medium, low).'),
  housingInformation: z.string().describe('Information about the housing or kandang of the ducks'),
});
export type PredictEggProductionInput = z.infer<typeof PredictEggProductionInputSchema>;

const PredictEggProductionOutputSchema = z.object({
  predictedEggProduction: z
    .number()
    .describe('The predicted number of eggs that will be produced tomorrow.'),
  reasoning: z.string().describe('The AI reasoning behind the predicted egg production.'),
});
export type PredictEggProductionOutput = z.infer<typeof PredictEggProductionOutputSchema>;

export async function predictEggProduction(input: PredictEggProductionInput): Promise<PredictEggProductionOutput> {
  return predictEggProductionFlow(input);
}

const predictEggProductionPrompt = ai.definePrompt({
  name: 'predictEggProductionPrompt',
  input: {schema: PredictEggProductionInputSchema},
  output: {schema: PredictEggProductionOutputSchema},
  prompt: `Anda adalah asisten manajemen peternakan AI yang berspesialisasi dalam memprediksi produksi telur.

  Berdasarkan informasi yang diberikan tentang bebek, kondisi mereka, kualitas pakan, dan perkandangan,
  prediksi jumlah telur yang akan diproduksi besok dan berikan alasan singkat untuk prediksi Anda dalam Bahasa Indonesia.

  Data Peternakan:
  - Jumlah Bebek: {{{duckQuantity}}}
  - Rata-rata Usia Bebek (Bulan): {{{duckAgeMonths}}}
  - Kondisi Bebek: {{{duckCondition}}}
  - Kualitas Pakan: {{{feedQuality}}}
  - Informasi Kandang: {{{housingInformation}}}
  
  Berikan respons dalam format JSON berikut:
  {
    "predictedEggProduction": number,
    "reasoning": string
  }`,
});

const predictEggProductionFlow = ai.defineFlow(
  {
    name: 'predictEggProductionFlow',
    inputSchema: PredictEggProductionInputSchema,
    outputSchema: PredictEggProductionOutputSchema,
  },
  async input => {
    const {output} = await predictEggProductionPrompt(input);
    return output!;
  }
);
